# Generated by Django 4.1.5 on 2023-01-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_jobber', '0002_user_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='urls',
            field=models.TextField(default='N/A'),
        ),
    ]
